/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/actividad/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lugar/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]/directorio`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]/guia`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]/resenas`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/actividad/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/lugar/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/region/[id]/directorio`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/region/[id]/guia`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/region/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/region/[id]/resenas`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/actividad/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/lugar/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/region/${Router.SingleRoutePart<T>}/directorio${`?${string}` | `#${string}` | ''}` | `/region/${Router.SingleRoutePart<T>}/guia${`?${string}` | `#${string}` | ''}` | `/region/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/region/${Router.SingleRoutePart<T>}/resenas${`?${string}` | `#${string}` | ''}` | { pathname: `/actividad/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lugar/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]/directorio`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]/guia`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/region/[id]/resenas`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
